# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: pages
on:
  schedule:
    - cron: 9 * * * *
  workflow_dispatch:
  push:
    tags:
      - current-page
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  refresh-front-uuid:
    runs-on: ubuntu-latest
    steps:
      - id: curl-uuid
        env:
          REF_FRONT_UUID_PASS: ${{ secrets.REF_FRONT_UUID_PASS }}
        run: |
          AUTH_HDR="Authorization: Basic $(echo -n ":$REF_FRONT_UUID_PASS" | base64 -w0)"
          VITE_GQL_SRV_PASS="$(curl https://api.phantomports.com/refresh-front-uuid -H "$AUTH_HDR")"
          echo "VITE_GQL_SRV_PASS=$VITE_GQL_SRV_PASS" >> "$GITHUB_OUTPUT"
    outputs:
      VITE_GQL_SRV_PASS: ${{ steps.curl-uuid.outputs.VITE_GQL_SRV_PASS }}

  build-deploy:
    runs-on: ubuntu-latest
    needs: refresh-front-uuid
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      VITE_GQL_SRV_URI: https://api.phantomports.com/query
      VITE_GQL_SRV_PASS: ${{ needs.refresh-front-uuid.outputs.VITE_GQL_SRV_PASS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i
      - run: npm run build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - id: deployment
        uses: actions/deploy-pages@v4
